let shopItemsData = [{
        id: "jfhgbvnscs",
        name: "Fish",
        price: 200,
        desc: "fresh fish from lake victoria",
        img: "image/fish.jpeg",
    },
    {
        id: "ioytrhndcv",
        name: "Groceries",
        price: 250,
        desc: "Fresh and healthy from the farm to you",
        img: "image/fruit1.jpeg",
    },
    {
        id: "wuefbncxbsn",
        name: "Banana",
        price: 150,
        desc: "healthy,sweet,fresh banana from the kisii land to you",
        img: "image/bananas.jpeg",
    },
    {
        id: "thyfhcbcv",
        name: "Omena",
        price: 80,
        desc: "Calcium and proteinated omena from lake victoria",
        img: "image/omena.jpeg",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Onions",
        price: 100,
        desc: "Cheap and fresh from the farm you cannot cry while choping",
        img: "image/rabuon.jpeg"

    },
    {
        id: "iuertrywebncdjksadjk",
        name: "Sweet potatoes",
        price: 180,
        desc: "From the farm to you,,,sweet potatoes",
        img: "image/rabuon1.jpeg",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "Tomatoes",
        price: 200,
        desc: "Fresh ,sweet, juicy and healthy tomatoes available just by a click of a button",
        img: "image/tomato1.jpeg",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "Fruits",
        price: 390,
        desc: "Fresh and affordable good for health",
        img: "image/fruits.jpeg",
    },
    {
        id: "cbvxbcvsceldk",
        name: "Omena",
        price: 100,
        desc: "Delicious omena you cant afford to miss",
        img: "image/omena1.jpeg",
    },
    {
        id: "oiopijmjkhuihb",
        name: "tomatoes",
        price: 200,
        desc: "juicy and fresh ",
        img: "image/tomato.jpeg",
    },
    {
        id: "oiopijewyiohbjhib",
        name: "Irish potatoes",
        price: 320,
        desc: "Available and ready",
        img: "image/waru.jpeg",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "Potatoe",
        price: 350,
        desc: "from the mountain to your doorstep by a click of a button",
        img: "image/waru2.jpeg",
    },
];